### ISSUE TITLE
Add Python3 support

### ISSUE THREAD

**Issue by roeles** [skylines-project/py-xcsoar#15]
@Turbo87 Is trying to add Python3 support, but can't make python3 find the entry point.

**Comment by Turbo87** [comment]
What I did so far:

- I've added a `python-3` branch to this repo (https://github.com/skylines-project/py-xcsoar/commits/python-3)
- I've fixed the incompatible Python code on that branch
- I've enabled testing with Python 3.3 on that branch
- I've also forked `XCSoar` to https://github.com/skylines-project/XCSoar and added a `python-3` branch there too (https://github.com/skylines-project/XCSoar/commits/python-3)
- I've followed http://python3porting.com/cextensions.html to fix incompatible code and managed to make it compile without errors

Where I am currently stuck:

- When running the test suite on CI with the `python-3` branch I'm seeing an "ImportError: dynamic module does not define init function (PyInit_xcsoar)" error (see https://travis-ci.org/skylines-project/py-xcsoar/jobs/341808658)

Compared to what http://python3porting.com/cextensions.html#module-initialization describes we seem to need `__attribute__ ((visibility("default")))` to make the entry point visible to Python 2. I'm wondering if something similar might be needed for Python 3. Unfortunately adding the exact same thing doesn't seem to have any effect.

**Comment by Turbo87** [comment]
Resolved by #16  🎉
